### ISSUE TITLE
Copying templates for function nodes to the clipboard fails

### ISSUE THREAD

**Issue by SiemensBleuler** [mindsphere/node-red-contrib-mindconnect#104]
**Describe the bug**
Copying templates to the clipboard fails. This is the same for every of the four buttons.

**To Reproduce**

1. Automatically create DP Mapping
2. Click on of the four copy template buttons
3. Try to paste the clipboard to a function node

**Expected behavior**
Successful copy of templates.

**Screenshots**
![temp](https://user-images.githubusercontent.com/57528264/93341016-e6f11f00-f82d-11ea-83dd-73b2843a3299.png)

**Desktop (please complete the following information):**
 Chrome Windows 

**Additional context**

**Comment by sn0wcat** [comment]
@SiemensBleuler is this the same raspberry?

**Comment by sn0wcat** [comment]
@SiemensBleuler Do you have the same problems on https://playground.mindconnect.rocks when trying to copy the content? this one i can't reproduce ;)

**Comment by SiemensBleuler** [comment]
@sn0wcat I tried it out running a windows 10 client for testing. My local node-RED instance copies the values just fine in Chrome. Using the same browser accessing the Raspberry Pis in the same LAN fails. Tested for 1x Pi zero and 1x Pi 3B+.
Also testing in your playground works just fine using the same browser.

**Comment by sn0wcat** [comment]
@SiemensBleuler  found it... both bugs are connected to the old version of chromium, as it is still wide spread I will publish an updated version fixing the issues.

**Comment by sn0wcat** [comment]
published version 3.9.1 to fix this issue.
