### ISSUE TITLE
Error after adding new datapoint to MindShpere and on the flow

### ISSUE THREAD

**Issue by kihana** [mindsphere/node-red-contrib-mindconnect#111]
I get an error after adding new datapoint to MindShpere and on the flow. The error can be seen on the screen 1. Error message is "Error: Data doesn't match the configuration! Errors: [{"keyword":"enum","dataPath":"[0].dataPointId","schemaPath":"#/items/properties/dataPointId/enum","params":{"allowedValues":["1603711984242","1604069980274","1604309224658","1604313647455"]},"message":"should be equal to one of the allowed values"}]".

Deploy was done after changes. And restart flows was done too. The value for the old datapoint (Line_1.MA35.AnalyticSystem.FeIII.AncolyzerData.Actual) was sent to MindSpere but for the new datapoint (Line_1.ComPart.LinePhaseShiftAnglele) the value was not sent. It can be seen on screen 2. Datapoint settings on MindSphere side can be seen on screen 3.

When I open and close only Agent Information dialog from RSA 3072 Agent(mindconnect) node the value for the new datapoint starts to send to MindSphere without this error. See 4 and 5 screens.

MindConnect Node-RED Agent v3.10.0 was used in this case.

**To Reproduce**
1. Add datapoint, add variable to aspect and link them
2. Add inject node for the new datapoint 
3. deploy flow
4. See error on the screen 1

**Expected behavior**
Sending values of new datapoint to MindSphere after deploy flow without this error and without opening Agent Information dialog.

**Screenshots**
screen 1
![image](https://user-images.githubusercontent.com/26021226/98692448-319b9d00-2380-11eb-9767-ba24150740cd.png)

screen 2
![image](https://user-images.githubusercontent.com/26021226/98693263-1e3d0180-2381-11eb-92eb-8789b06c3f96.png)

screen 3
![image](https://user-images.githubusercontent.com/26021226/98693407-4dec0980-2381-11eb-81c8-3a2e96119566.png)

screen 4
![image](https://user-images.githubusercontent.com/26021226/98695000-2eee7700-2383-11eb-9fa8-718a2bb7d006.png)

screen 5
![image](https://user-images.githubusercontent.com/26021226/98695191-6a894100-2383-11eb-9668-76e25faf0e27.png)

**Node-RED server runs:**
 - OS: Windows 10 IoT Enterprise x64

**For configuration flow were used:**
 - safari and firefox

**Comment by sn0wcat** [comment]
@kihana could you try to pass `msg._forceGetConfig=true` parameter on the message to force the node to update the configuration? The reason why this could be happening is because the node caches the configuration once it retrieves it and if you make a change in mindsphere, you still have the old config in node-RED.

![image](https://user-images.githubusercontent.com/1426617/98706078-b2f23000-237e-11eb-9877-2eb61388b65f.png)

if it works, you can remove that parameter again and redeploy the flow.

**Comment by sn0wcat** [comment]
@kihana any luck with `msg._forceGetConfig` ?

**Comment by kihana** [comment]
Shortly no. It seems that it doesn't fit in my case.
When I add this flag manually to the new inject to add new datapoint it works well.

But my case is generating and deploying flow programmatically. So I modified my deploying algorithm according your advice. The first step during generation the flow all inject nodes were added with `msg._forceGetConfig=true` option and then the flow was deployed using Node-RED API (https://nodered.org/docs/api/admin/methods/post/flows/). The second step during generation the flow all inject nodes were added without that option and then the flow was deployed one more time. And after that I got errors (see screen 1). The flow which was deployed on these two steps can be seen on screen 2. After getting these errors I restart flow without any modifications (screen 3) and all data goes to MindSphere without any errors an I can see them in Fleet Manager. screen 2 was made after this step.

screen 1
![image](https://user-images.githubusercontent.com/26021226/98866196-a0125500-247d-11eb-9eab-b6200f1fbffb.png)

screen 2
![image](https://user-images.githubusercontent.com/26021226/98866347-d8199800-247d-11eb-9d53-f7d63b93d515.png)

screen 3
![image](https://user-images.githubusercontent.com/26021226/98866561-30e93080-247e-11eb-860b-7b970ba5a26d.png)

**Comment by sn0wcat** [comment]
@kihana If you are deploying the flows programmatically and you are sure that the configuration is right, you could also try to switch off the validation in the node. That way the data will just be sent to the MindSphere without any client-side validation.  

![image](https://user-images.githubusercontent.com/1426617/98897826-96541600-24ac-11eb-8f25-53201f83cee8.png)

**Comment by kihana** [comment]
Thanks a lot.
