### ISSUE TITLE
Not able to check "msg._mindsphereStatus" in version 3.9+

### ISSUE THREAD

**Issue by EliasReuter** [mindsphere/node-red-contrib-mindconnect#112]
Dear Support,

As described in the main guide of this not, in order to check the upload status of my datapoints, i have an switch node to check if the attribute "msg._mindsphereStatus" is getting an "OK" or not "OK" value, in order to feed the offline buffer flow we designed if it doesn't uploaded right. (Mention to issue #20 )
This used to work fine for buffering the packages that either didn't upload consequence of instable internet connection, but also for making more stable the upload rate (for some reason, some packages didn't upload right, maybe because of saturation) catching the one that didn't uplaod right.
This is the logic: (If you have any suggestions to make it better, we are open to improve it and share it with the community)
![image](https://user-images.githubusercontent.com/40266095/100871722-7b5b3d00-347f-11eb-99da-8d96885bd287.png)

The problem is, now that we downloaded the (almost?) lastest version of this node, we are not able to check the mentioned "msg._mindsphereStatus" attribute to either finish the execution of the succesful uploads, or feed the buffering flow when we are offline.
![image](https://user-images.githubusercontent.com/40266095/100871667-68486d00-347f-11eb-8b9a-90750f559fec.png)

Mindconnect Node configuration:
![image](https://user-images.githubusercontent.com/40266095/100872212-3683d600-3480-11eb-9aa9-7fdbf6f22217.png)
![image](https://user-images.githubusercontent.com/40266095/100872229-3edc1100-3480-11eb-9baf-f3da3c640f2c.png)

Description of error:
If we disconnect the device from internet (disconnect cable) in which this Flow is running, we are accumulating a lot of request in the MindConnect Node, instead of "failing the upload", setting an "Not OK" state for every failed json and feeding the offline buffer flow.
![image](https://user-images.githubusercontent.com/40266095/100873403-f58cc100-3481-11eb-97c8-b94331396c4f.png)
 
Is the node already buffering on its own? If so, i tried it out and its not able to handle hours of buffering (in my test case, i can try again if you say so) 
If not, why isn't the node outputting every package with the attribute "msg._mindsphereStatus = Error" as it used to do? 

Thank you

**Comment by sn0wcat** [comment]
@EliasReuter the node is not buffering anything, I will take a look.

**Comment by sn0wcat** [comment]
@EliasReuter I am having a hard time reproducing this. If I pull the network from under node-red the node sends the error as expected. Here is the behavior I can observe:

https://vimeo.com/486435611

Could you restart your flow / redeploy flow fully and try again? If you still have a problem ping me tomorrow on teams, I wrote to you.

**Comment by sn0wcat** [comment]
todo:
- provide a better example for high load / buffering flow on playground.mindconnect.rocks

**Comment by sn0wcat** [comment]
@EliasReuter  i will provide a new alpha version today with examples for high load / buffering - the node has also been changed to alleviate some of your problems
