### ISSUE TITLE
Mindsphere node V3.10.0 gives error in IOT2040

### ISSUE THREAD

**Issue by rawrahul** [mindsphere/node-red-contrib-mindconnect#118]
**Describe the bug**

Error: Network error occured request to https://southgate.eu1.mindsphere.io/api/agentmanagement/v3/register failed, reason: getaddrinfo EAI_AGAIN southgate.eu1.mindsphere.io:443

**To Reproduce**
1. install or update Mindsphere V3.10.0 node in IOT2040

 Node-RED version: v0.20.7
 Node.js  version: v8.16.0
 Linux 4.4.185-cip35 ia32 LE

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

** MindSphere Plan **
- start for free 
- iot value plan 
- developer plan
- operator plan

**Additional context**

**Comment by sn0wcat** [comment]
@rawrahul 

EAI_AGAIN is a DNS lookup error, your device probably doesn't have / can't reach its domain name server and therefore the error message appears. This is something which has to be solved on the OS level of the device running the node-red node. 

try running 
```nslookup southgate.eu1.mindsphere.io```

from the command line on the device.

https://www.codingdefined.com/2015/06/nodejs-error-errno-eaiagain.html

**Comment by sn0wcat** [comment]
iot2040 forum is the best place for more infos about troubleshooting the problems on iot2040 : https://support.industry.siemens.com/tf/ww/en/threads/303/?page=0&pageSize=10

**Comment by rawrahul** [comment]
@sn0wcat You are right. I configured second port of IOT2040 as static IP and disconnected from internet. This has resolved now.
Thank you very much for your help.
