### ISSUE TITLE
Typo in the sample flow for IDL upload

### ISSUE THREAD

**Issue by peterandree** [mindsphere/node-red-contrib-mindconnect#124]
**Describe the bug**
A typo in the function node invalidates the flow,

**To Reproduce**
see screenshot

**Expected behavior**

**Screenshots**
![2021-03-19 11_01_44-Window](https://user-images.githubusercontent.com/7920431/111763536-8d33e500-88a2-11eb-9cfb-c466543278f5.png)

**Additional context**
in node "send new files to data lake" line 12 should be
    dataLakeFilePath: `uploads/${new Date().getTime()}/${msg.payload}`

(note the capital F in FilePath)

**Comment by sn0wcat** [comment]
thanks, i was in the middle of the editing, already fixed :)
