### ISSUE TITLE
HTTP Status (500 Internal Error)

### ISSUE THREAD

**Issue by selko** [mindsphere/node-red-contrib-mindconnect#152]
I connect MindConnect Lib doing onboarding process and it is onboarded. 
But i´m getting error in Agent Configuration:

ERROR: HTTP Status 500 - Internal Server Error.
Console in Node-Red
<------
Error: Network error occured Network error occured Internal Server Error <!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1></body></html>
--->
In Agent Configuration:

![Captura](https://user-images.githubusercontent.com/6910544/157670865-fe2c68b6-3951-430c-999d-050fd46fe7f2.JPG)

Some help would be appreciated.

Kind regards!

**Comment by sn0wcat** [comment]
@selko this is happening because mindsphere has a major outage in agent management at the moment. We have to wait and see when this will be fixed.
https://status.mindsphere.io/
![image](https://user-images.githubusercontent.com/1426617/157850097-ee92a66c-23d8-48ad-8d75-d44f11de01c2.png)

**Comment by selko** [comment]
Ok, it is working now. Thanks for your response. I didn´t know that i can check the status of different sevrvices.
Thank you and kind regards.
