### ISSUE TITLE
Don´t know how to see data received from node-red mindconnect in mindsphere.

### ISSUE THREAD

**Issue by selko** [mindsphere/node-red-contrib-mindconnect#153]
we can send data to Mindsphere but we dont know how to see this values in MindSPhere. We were trying see but we dont find how to.

![image](https://user-images.githubusercontent.com/6910544/158324661-ee8be3a5-dd69-443f-82f1-62565021945f.png)

We follow some documentation. Something is missing.

 
This is an example of one boolean variable and i wanted to see in table and time how it´s changing (from 0 to 1).

We have more variables but knowing how to see this one we can try by my own.

 
![image](https://user-images.githubusercontent.com/6910544/158324733-a6df2906-a0c7-4370-83b1-a453fdd52596.png)

If someone can help me or tell me how to see these variables values in mindsphere i would appreciate it.

![image](https://user-images.githubusercontent.com/6910544/158324792-6b46aa2a-6af0-4347-b08a-519fa8df184e.png)

![image](https://user-images.githubusercontent.com/6910544/158324807-d7c4ff1e-d7f1-4c28-b0eb-6386cc196794.png)

Thank you in advance and kind regards

**Comment by sn0wcat** [comment]
lets continue the discussion in the forum.

https://community.sw.siemens.com/s/question/0D54O00007NeXltSAF/see-data-current-variables-received-from-nodered-mindconnect-lib?t=1647331842383&_ref=dD0xNjQ3MzMxODQyMzgz

**Comment by selko** [comment]
ok, sorry for duplicate. I  didn´t know that are the same. Thank you!
