### ISSUE TITLE
feat: better support for offline buffering

### ISSUE THREAD

**Issue by sn0wcat** [mindsphere/node-red-contrib-mindconnect#20]
When the MindSphere is offline it would be nice to have a support for bulk-upload of the buffered data.

**Describe alternatives you've considered**
An alternative is to create a separate flow which will handle the buffered data.

**Additional context**
This feature requires the MindSphere to support bulk upload for performance assets.

**Comment by EliasReuter** [comment]
**Question**
Is the purpose of this feature just too improve the node's "bulk-upload" of the buffered data? (buffered with other node-red logic)
Or does it also include the buffering functionality within the node (when the node can't connect to mindsphere/is offline saves a certain amount of data) and then bulk upload the buffered data when connection is reestablished?

**Comment by sn0wcat** [comment]
@EliasReuter buffering within the node. This can be solved already now with buffering in the flow using more sofisticated flow design.

**Comment by EliasReuter** [comment]
@sn0wcat Great feature 💡
Do you have any example of this sophisticated buffering flow you mentioned?
Is there any estimated release date for this feature/version 3.9.0?

Thank you 👍

**Comment by rcarreir** [comment]
Hi. I've been trying to make my own buffering flow but I've not been successful. It would be very helpfull if you have any example of how you solved it so us to give it a try.  @sn0wcat 
Thank you!

**Comment by sn0wcat** [comment]
@rcarreir could you post what you were trying to do?

**Comment by sn0wcat** [comment]
@rcarreir @EliasReuter  take a look at the new flows which can buffer the data if the node is under high pressure

https://playground.mindconnect.rocks/#flow/676a86e4.fe7888
