### ISSUE TITLE
Failed to load mindconnect node when modifying the URL root path

### ISSUE THREAD

**Issue by dbaba** [mindsphere/node-red-contrib-mindconnect#3]
**Describe the bug**
mindsphere.css and ajv.min.js failed to be loaded from browser when providing `httpAdminRoot` in `settings.js` file in order to configure URL base path.
The way to modify the root path is described in [Node-RED official document](https://nodered.org/docs/configuration).

**To Reproduce**
1. Edit `settings.js` and insert `httpAdminRoot: 'mypath'`
2. Start Node-RED and access to `http://localhost:1880/mypath` on a local browser
3. The browser complains as CSS and JS resources are missing (HTTP 404 error for the resources)
4. Node-RED editor also shows a dialog saying `Failed to load '@mindconnect/node-red-contrib-mindconnect/mindconnect' SyntaxError: expected expression, got '<'` on the browser

**Expected behavior**
The both resources should be loaded without errors.

**Screenshots**
Node-RED editor error:
![screenshot1](https://user-images.githubusercontent.com/1858156/52454957-48043b80-2b91-11e9-9ca9-5c504fc0f874.jpg)
Browser errors:
![unnamed](https://user-images.githubusercontent.com/1858156/52454985-6407dd00-2b91-11e9-946d-4f5a9fc41c73.jpg)

**Desktop**
 - OS: macOS 10.13.6, Raspbian Stretch (2018-10-09)
 - Browser Safari 12.0.3

**Smartphone (please complete the following information):**

**Additional context**
I found a solution to the issue. Just remove '/' from `href` attribute values.

```
$ diff node-red-contrib-mindconnect/src/mindconnect.html.resolved node-red-contrib-mindconnect/src/mindconnect.html
1c1
< <link href="mindsphere.css" rel="stylesheet">
---
> <link href="/mindsphere.css" rel="stylesheet">
177c177
< <script type="text/javascript" src="ajv.min.js" />
---
> <script type="text/javascript" src="/ajv.min.js" />
```

**Comment by sn0wcat** [comment]
Done. The bugfix will be published to npm with the next version. @dbaba  Thanks for the find. 👍

**Comment by dbaba** [comment]
Thanks for the quick action.
Could you please tell me when is the next version rolled out?

**Comment by sn0wcat** [comment]
@dbaba today 😹
