### ISSUE TITLE
Bulk upload not posting data - MC node says successful

### ISSUE THREAD

**Issue by Peekaboo-Cockatoo** [mindsphere/node-red-contrib-mindconnect#48]
**The bug**
When posting dynamic data using the bulk upload format, the MindConnect node returns  "Posted last bulk message at {{current_time}}", however the data is not visible on MindSphere. Using APIs to query the respective asset I am returned "[]" which indicates no data was posted.
The original occurence came about as I was grabbing serial data at a 1 second polling rate, decoding it then posting it to MindSphere using a SimaticIOT2040. To reduce the CPU usage and to alleviate the stress on the device/node, I collected packets of data for about 20 seconds put them into the bulk format then passed on the payload to the MindConnect Node.
Strangely enough, when the bulk format is used with only one variable in each msg.payload.value object the data is visible on MindSphere. But when each msg.payload.value object carries multiple values they don't seem to get posted.

**To Reproduce**
I have attached simplified flows I've been using to debug (I've removed the shared secret from the MindConnect nodes). 
One flow produces multiple values in the value object (flowFail.txt)
The other flow produces one value per value object (flowSuccess.txt)

[flowFail.txt](https://github.com/mindsphere/node-red-contrib-mindconnect/files/3425488/flowFail.txt)
[flowSuccess.txt](https://github.com/mindsphere/node-red-contrib-mindconnect/files/3425489/flowSuccess.txt)

**Screenshots**
In the following images you can see the flow (flowFail) displaying a successful post notification, but on FleetManager and through Postman (using the timeseries APIs on the relevant asset) you can see that no data ever made it to MindSphere.

![flow](https://user-images.githubusercontent.com/53249254/61772697-3f00e100-ae36-11e9-9e66-ebbd3724785c.PNG)

![fleetManager](https://user-images.githubusercontent.com/53249254/61772727-5213b100-ae36-11e9-9653-d7c6026d3606.PNG)

![postman](https://user-images.githubusercontent.com/53249254/61772753-648dea80-ae36-11e9-8815-ecb392f80610.PNG)

**Version Information**
Node-Red Version 0.20.6
MindConnect Node Version 3.6.1

**Additional context**
I have also attached some output JSON named "msgFail.txt" and "msgSuccess.txt".

[msgFail.txt](https://github.com/mindsphere/node-red-contrib-mindconnect/files/3425478/msgFail.txt)
[msgSuccess.txt](https://github.com/mindsphere/node-red-contrib-mindconnect/files/3425479/msgSuccess.txt)

**Comment by sn0wcat** [comment]
@Peekaboo-Cockatoo At the first glance, you are using the local time stamp instead of the UTC time stamps in your msgFail.txt. Could you please convert those time stamps to UTC and try again ? (Sorry for the brevity, I am on vacation....)

**Comment by Peekaboo-Cockatoo** [comment]
@sn0wcat Changing the timestamp to UTC gives the exact same result unfortunately.

**Comment by sn0wcat** [comment]
@Peekaboo-Cockatoo Have you already checked in the agent diagnostic app (on your launchpadj and/or talked to the support if MindSphere is dropping your data because of some misconfiguration / problem on the MindSphere side? When the agent says that the data has been delivered , it only means that the ingest endpoint has accepted them, not that the data has been stored in the iot or the aggregates have been built (these are both asynchronous processes) .

**Comment by Peekaboo-Cockatoo** [comment]
@sn0wcat  Agent Diagnostics returns:


[Dropped] TimeSeries Data is dropped. Validation failed for reason <Pre-processing of <21> data points ended with <0> valid and <21> dropped data points. Following issues found: Invalid timestamps count is <7> resulting <21> data point value to be dropped.Invalid timestamps includes: <[Tue, 30 Jul 2019 01:31:14 GMT, Tue, 30 Jul 2019 01:31:17 GMT, Tue, 30 Jul 2019 01:31:20 GMT, Tue, 30 Jul 2019 01:31:23 GMT, Tue, 30 Jul 2019 01:31:26 GMT, Tue, 30 Jul 2019 01:31:29 GMT, Tue, 30 Jul 2019 01:31:32 GMT]>.>
--

I'll contact MindSphere Support and let you know the results.

**Comment by Peekaboo-Cockatoo** [comment]
Okay, so I have got it working. MindSphere was rejecting the data because of the timestamp format.
I was using the "toString()" function, which let it pass the MindConnect node checks but then obviously it got rejected.
To create a timestamp with "new Date()" would return a huge list of errors.  It was just a matter of using the toISOString() function.

So in the end my timestamps would be made as such:
    var timestamp = new Date().toISOString();
    dict.timestamp = timestamp;

I'm quite a novice programmer, so I hope this info can help others like me in the future. Is it possible to add some tidbit like this to the docs for the bulk upload section?

Thanks for taking the time to assist in getting it all working!

**Comment by sn0wcat** [comment]
The documentation has been updated. 


https://opensource.mindsphere.io/docs/node-red-contrib-mindconnect/getting-started.html#tab1anchor3
