### ISSUE TITLE
Timestamp doesn't accept new Date()

### ISSUE THREAD

**Issue by austrisu** [mindsphere/node-red-contrib-mindconnect#51]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sn0wcat** [comment]
@austrisu as the description is not very clear I will have to guess that you are using bulk upload. In that case you have to send the timestamp as ISO String ```new Date().toISOString()```

```
 timestamp: new Date().toISOString()
```

as described here:

https://opensource.mindsphere.io/docs/node-red-contrib-mindconnect/getting-started.html#tab1anchor3

```javascript
Send data points in bulk
The node requires json objects as input in following format (e.g. from a function node if you want to use bulk upload)

const values = [
  {
    timestamp: "2018-11-09T07:46:36.699Z",
    values: [
      { dataPointId: "1000000000", qualityCode: "1", value: "42" },
      { dataPointId: "1000000001", qualityCode: "1", value: "33.7" },
      { dataPointId: "1000000003", qualityCode: "1", value: "45.76" }
    ]
  },
  {
    timestamp: "2018-11-08T07:46:36.699Z",
    values: [
      { dataPointId: "1000000000", qualityCode: "1", value: "12" },
      { dataPointId: "1000000001", qualityCode: "1", value: "13.7" },
      { dataPointId: "1000000003", qualityCode: "1", value: "15.76" }
    ]
  }
];

msg.payload = values;
return msg;
```

***Note: All MindSphere timestamps must be in the ISO format (use toISOString() function).***


See also demo flows:

https://playground.mindconnect.rocks

**Comment by sn0wcat** [comment]
See also #48
