### ISSUE TITLE
Does not work on windows 10 IOT

### ISSUE THREAD

**Issue by zsoni96** [mindsphere/node-red-contrib-mindconnect#69]
I've tried this node on multiple devices/ platforms it worked well in all of them expect on win10 iot.

I installed it from node-red first, it did not copy the files to node_modules.After installing it from cmd the files were installed, but the node is still no displayed in node-red.
I tried to install it multiple ways with a lot of rehosting the server or restarting the pc. None of them worked.

**Comment by sn0wcat** [comment]
@zsoni96 could you add more details about node-red and node version on windows iot?

**Comment by zsoni96** [comment]
@sn0wcat  I used the same version on all devices which is
 Node-RED version: v1.0.3
 Node.js  version: v12.14.1

**Comment by sn0wcat** [comment]
@zsoni96 do you have by any chance a docker image or a system where I could take a look at your problem?

**Comment by sn0wcat** [comment]
@zsoni96 see above :)
