### ISSUE TITLE
Node incompatible with Node-RED 1.10?

### ISSUE THREAD

**Issue by SiemensBleuler** [mindsphere/node-red-contrib-mindconnect#90]
After upgrading NR to 1.10 and the Mindconnect node to 3.7 it is not showing up in the node list anymore.

Flows that use the node show it as if it wasnt installed at all although it is.

Reinstalling the node, restarting node-RED wont't fix it. Starting from scratch with a fresh node-red install wont either. Tested on a raspi and a win10 installation.

![MCISSUE1](https://user-images.githubusercontent.com/57528264/86366854-9a109a00-bc7b-11ea-8c6c-fe3de8b807d6.PNG)
![MCISSUE2](https://user-images.githubusercontent.com/57528264/86366856-9aa93080-bc7b-11ea-9dae-b1f247a3094a.PNG)

**Comment by sn0wcat** [comment]
I can reproduce it. It seems that something has changed in the way how the node-red is loading the nodes, please stay wit h 1.0.6 for now until I found out what is going on. (I contacted the node-RED developers to take a look)

**Comment by sn0wcat** [comment]
The error has been fixed and a release 3.8.0. has been published. 

The background of the issue:

The node-red 1.10 has implemented strict HTML checking and the node had a <script .../> instead of <script></script> tag.

Fixed in 3.8.0

**Comment by sn0wcat** [comment]
see https://playground.mindconnect.rocks
