### ISSUE TITLE
Token validation failed

### ISSUE THREAD

**Issue by EliasReuter** [mindsphere/node-red-contrib-mindconnect#94]
We're connecting an IoT2040 to mindsphere with NodeRed and this node installed in it.
Onboarding and uploading data works fine. But after sometime occures an token validation error.
Does this node automatically refresh its token or should we do that logic in node red? 
In that second case, how would you recommend us to to so?

Error: Network error occured Unauthorized {
    "error": "token_validation_failed",
    "error_description": "[335deceb801f48d1b49847f8bee61223]"
}

Error: Network error occured Unauthorized 
{
    "error": "token_validation_failed",
    "error_description": "[96004b0a4fef4b3b847946eb1f2c03bb]"
}

Thank you 👍

**Comment by sn0wcat** [comment]
The node is donig automatic refresh of the token unless its disabled.  Which version of the node are you using?

![image](https://user-images.githubusercontent.com/1426617/86773762-3c52c800-c056-11ea-904d-c0196a0aa872.png)

see also https://playground.mindconnect.rocks

**Comment by sn0wcat** [comment]
@EliasReuter for the case that you were using one of the earlier versions, there was a bug in the keep alive function:

https://opensource.mindsphere.io/docs/mindconnect-nodejs/troubleshooting.html#tab1anchor3 (see mitigation for versions before 3.7.0)

**Comment by EliasReuter** [comment]
@sn0wcat 
Customer didn't answer yet, but i guess they do have an earlier version of it.
Thank you for this last last keep alive function. It will help.

Thank you for the support. 🥇
